name: "Setup Python"
description: "install python and poetry, then install python packages with poetry."
inputs:
  python-version:
    default: "3.x"
    required: false
    description: 'version of python'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - uses: abatilo/actions-poetry@v2.1.4
    - run: poetry install
      shell: bash
