name: "Setup Python"
description: "install python and poetry, then install python packages with poetry."
inputs:
  python-version:
    default: "3.x"
    required: false
    description: 'version of python'
runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pip install poetry
      shell: bash
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry
    - name: Install python packages
      run: poetry install
      shell: bash
