name: "Setup Python"
description: "install python and poetry, then install python packages with poetry."
inputs:
  python-version:
    default: "3.x"
    required: true
    description: "version of python"
  poetry-version:
    default: "1.5.1"
    required: true
    description: "version of poetry"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      run: pip install poetry==${{ inputs.poetry-version }}
      shell: bash
    - name: Install python packages
      run: poetry install
      shell: bash
