name: code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with pytest
      run: poetry run pytest

  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: ./.github/actions/setup-python
    - name: Test with pytest
      run: poetry run pytest --cov=algorithms --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: ./.github/actions/setup-python
    - name: Check with flake8
      run: poetry run flake8
    - name: Check with black
      run: poetry run black . --check --diff
    - name: Check with isort
      run: poetry run isort . --check --diff
