name: build

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install
    - name: Lint with markdownlint
      run: yarn run markdownlint docs
    - name: Lint with textlint
      run: yarn run textlint docs

  build-deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@master
      if: contains(github.ref, 'master')

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
      if: contains(github.ref, 'master')
    - name: Build
      run: |
        pip install mkdocs mkdocs-material pymdown-extensions
        mkdocs build
      if: contains(github.ref, 'master')

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
      if: contains(github.ref, 'master')
