name: docs

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - run: yarn install
    - name: Lint with markdownlint
      run: yarn run markdownlint docs
    - name: Lint with textlint
      run: yarn run textlint docs

  build-deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: ./.github/actions/setup-python
      with:
        python-version: "3.9"
    - name: Build
      run: poetry run mkdocs build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
