name: lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Lint with black
      run: |
        pip install black
        black . --check

    - name: Set up Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Lint with markdownlint
      run: |
        npm install
        npm run lint
